// AUTO-GENERATED by model/generate.py from params.yaml — DO NOT EDIT BY HAND.
#pragma once
#include <stdint.h>

#define N_JOINTS 12
#define SERVO_FREQ_HZ 50

struct ServoCal {
  const char* name;
  uint8_t channel;
  float lower, upper, default_q;
  float pwm_min, pwm_max, angle_min, angle_max;
  int8_t direction;
  float zero_offset;
};

static const ServoCal SERVOS[N_JOINTS] = {
  {"FL_hip", 0, -0.8f, 0.8f, 0.0f, 500.0f, 2500.0f, -2.356f, 2.356f, 1, 0.0f},
  {"FL_thigh", 1, -1.6f, 1.6f, 0.7f, 500.0f, 2500.0f, -2.356f, 2.356f, 1, 0.0f},
  {"FL_knee", 2, -2.6f, -0.2f, -1.4f, 500.0f, 2500.0f, -2.356f, 2.356f, 1, 1.4f},
  {"FR_hip", 3, -0.8f, 0.8f, 0.0f, 500.0f, 2500.0f, -2.356f, 2.356f, 1, 0.0f},
  {"FR_thigh", 4, -1.6f, 1.6f, 0.7f, 500.0f, 2500.0f, -2.356f, 2.356f, 1, 0.0f},
  {"FR_knee", 5, -2.6f, -0.2f, -1.4f, 500.0f, 2500.0f, -2.356f, 2.356f, 1, 1.4f},
  {"RL_hip", 6, -0.8f, 0.8f, 0.0f, 500.0f, 2500.0f, -2.356f, 2.356f, 1, 0.0f},
  {"RL_thigh", 7, -1.6f, 1.6f, 0.7f, 500.0f, 2500.0f, -2.356f, 2.356f, 1, 0.0f},
  {"RL_knee", 8, -2.6f, -0.2f, -1.4f, 500.0f, 2500.0f, -2.356f, 2.356f, 1, 1.4f},
  {"RR_hip", 9, -0.8f, 0.8f, 0.0f, 500.0f, 2500.0f, -2.356f, 2.356f, 1, 0.0f},
  {"RR_thigh", 10, -1.6f, 1.6f, 0.7f, 500.0f, 2500.0f, -2.356f, 2.356f, 1, 0.0f},
  {"RR_knee", 11, -2.6f, -0.2f, -1.4f, 500.0f, 2500.0f, -2.356f, 2.356f, 1, 1.4f},
};
