// AUTO-GENERATED by model/generate.py from params.yaml — DO NOT EDIT BY HAND.
#pragma once
#include <stdint.h>

#define N_JOINTS 8
#define SERVO_FREQ_HZ 50

struct ServoCal {
  const char* name;
  uint8_t channel;
  float lower, upper, default_q;
  float pwm_min, pwm_max, angle_min, angle_max;
  int8_t direction;
  float zero_offset;
};

static const ServoCal SERVOS[N_JOINTS] = {
  {"FL_abd", 0, -1.0f, 1.0f, 0.45f, 500.0f, 2500.0f, -2.356f, 2.356f, 1, 0.0f},
  {"FL_knee", 1, -1.5f, 1.5f, 0.7f, 500.0f, 2500.0f, -2.356f, 2.356f, 1, 0.0f},
  {"FR_abd", 2, -1.0f, 1.0f, 0.45f, 500.0f, 2500.0f, -2.356f, 2.356f, 1, 0.0f},
  {"FR_knee", 3, -1.5f, 1.5f, 0.7f, 500.0f, 2500.0f, -2.356f, 2.356f, 1, 0.0f},
  {"RL_abd", 4, -1.0f, 1.0f, 0.45f, 500.0f, 2500.0f, -2.356f, 2.356f, 1, 0.0f},
  {"RL_knee", 5, -1.5f, 1.5f, 0.7f, 500.0f, 2500.0f, -2.356f, 2.356f, 1, 0.0f},
  {"RR_abd", 6, -1.0f, 1.0f, 0.45f, 500.0f, 2500.0f, -2.356f, 2.356f, 1, 0.0f},
  {"RR_knee", 7, -1.5f, 1.5f, 0.7f, 500.0f, 2500.0f, -2.356f, 2.356f, 1, 0.0f},
};
